### ISSUE TITLE
Disabled action-link

### ISSUE THREAD

**Issue by erikhallaraaker** [SwedbankPay/design.swedbankpay.com#177]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when my project needs a disabled `.action-link` and there is none in the designguide.

**Describe the solution you'd like**

I'd like a disabled action link, could be `.action-link-disabled`.

**Describe alternatives you've considered**

I have considered, and implemented a custom disabled action-link in our project. Might be useful to include something like this in the designguide.

**Additional context**

![image](https://user-images.githubusercontent.com/6810727/65498914-05dc0000-debd-11e9-956c-84a9852847c4.png)

**Possible Implementation**

This is how we implemented it in our solution.

```css
a.action-link.action-link-disabled {
    background: #f9f8f6;
}
a.action-link.action-link-disabled p,
a.action-link.action-link-disabled small,
a.action-link.action-link-disabled h3 {
    color: #767676;
}
a.action-link.action-link-disabled:hover {
    cursor: not-allowed;
}
a.action-link.action-link-disabled::before {
    background: #999999;
}
a.action-link.action-link-disabled::after {
    display: none;
}
```
